fix using script directory rather than absolute path

diff --git a/get-backup-id b/get-backup-id
--- a/get-backup-id
+++ b/get-backup-id
@@ -1,3 +1,11 @@
 #!/bin/bash
 
-/mnt/disks/apps/duplicati/scripts/duc list backups | awk "f{print \$2;f=0} /$1/{f=1}" | sed s/\'//g
+if [[ $# == 0 ]]; then
+    printf "[ERROR] usage: get-backup-id <filesystem>\n"
+    exit 1
+fi
+
+# Absolute path this script is in
+SCRIPT_DIR=$(dirname $(readlink -f "$0"))
+
+$SCRIPT_DIR/duc list backups | awk "f{print \$2;f=0} /$1/{f=1}" | sed s/\'//g
diff --git a/get-backup-name b/get-backup-name
--- a/get-backup-name
+++ b/get-backup-name
@@ -1,3 +1,11 @@
 #!/bin/bash
 
-/mnt/disks/apps/duplicati/scripts/duc list backups | fgrep $1 | sed "s/^- //g" | sed "s/:$//"
+if [[ $# == 0 ]]; then
+    printf "[ERROR] usage: get-backup-name <filesystem>\n"
+    exit 1
+fi
+
+# Absolute path this script is in
+SCRIPT_DIR=$(dirname $(readlink -f "$0"))
+
+$SCRIPT_DIR/duc list backups | fgrep $1 | sed "s/^- //g" | sed "s/:$//"
